AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Jersey API - ivyzhangAWS::Serverless
Resources:
  ServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ivyzhangAWS.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/Serverless-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  ServerlessApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: ServerlessApi
